name: Terraform Plan

on:
  workflow_dispatch:
    inputs:
      plan:
        description: 'Executar Terraform Plan?'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
permissions:
  contents: read
  id-token: write

jobs:
  plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./infra
        
    steps: 
      - name: 'Checkout'
        uses: actions/checkout@v5.0.0
      
      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          role-to-assume: arn:aws:iam::215436574250:role/GithubInfraRole
          aws-region: us-east-1 

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.5
          terraform_wrapper: true
      
      - name: 'Terraform Init'
        run: terraform init
      
      - name: 'Terraform Validate'
        run: terraform validate
      
      - name: 'Terrform Fmt'
        run: terraform fmt -check -recursive 
        
      - name: 'Terraform Plan'
        run: terraform plan -out=tfplan
        if: github.event.inputs.plan == 'true'
