name: Terraform CI/CD

on:
  workflow_dispatch:
    # Entradas manuais que decidem quais etapas serão executadas
    inputs:
      plan:
        description: 'Executar Terraform Plan?'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
      apply:
        description: 'Executar Terraform Apply?'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
      plan_destroy:
        description: 'Planejar Terraform Destroy?'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
      destroy:
        description: 'Executar Terraform Destroy?'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

permissions:
  contents: read
  id-token: write

# Variáveis globais reutilizadas em todos os jobs
env:
  AWS_REGION: us-east-1
  ROLE_TO_ASSUME: arn:aws:iam::215436574250:role/GithubInfraRole
  TERRAFORM_VERSION: 1.15.5
  WORKING_DIRECTORY: ./infra

jobs:
  # 1. Job de Plan: Valida o código e cria um plano do que será alterado
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    if: github.event.inputs.plan == 'true' || github.event.inputs.apply == 'true'
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5.0.0
      
      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      
      - name: 'Terraform Init'
        run: terraform init
        
      - name: 'Terraform Validate'
        run: terraform validate
        
      - name: 'Terraform Fmt'
        run: terraform fmt -check -recursive 
        
      # Instala o TFLint no runner
      - name: 'Setup TFLint'
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: latest

      # Executa a verificação estática (Lint) para achar erros não triviais e melhorar a qualidade do código Terraform
      - name: 'Run TFLint'
        run: tflint -f compact
        

      - name: 'Terraform Plan'
        run: terraform plan -out=tfplan

      - name: 'Upload Plan Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ${{ env.WORKING_DIRECTORY }}/tfplan
          retention-days: 1

  # 2. Job de Apply: Baixa o plano criado anteriormente e aplica na AWS
  terraform-apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: github.event.inputs.apply == 'true'
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5.0.0
      
      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Download Plan Artifact'
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ${{ env.WORKING_DIRECTORY }}
        
      - name: 'Terraform Apply'
        run: terraform apply -auto-approve tfplan

  # 3. Job de Plan Destroy: Planeja a destruição da infraestrutura
  terraform-plan-destroy:
    name: 'Terraform Plan Destroy'
    runs-on: ubuntu-latest
    needs: terraform-apply
    if: |
      always() && 
      (needs.terraform-apply.result == 'success' || needs.terraform-apply.result == 'skipped') &&
      (github.event.inputs.plan_destroy == 'true' || github.event.inputs.destroy == 'true')
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5.0.0
      
      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      
      - name: 'Terraform Init'
        run: terraform init
        
      - name: 'Terraform Plan Destroy'
        run: terraform plan -destroy -out=tfplan_destroy

      - name: 'Upload Plan Destroy Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: tfplan_destroy
          path: ${{ env.WORKING_DIRECTORY }}/tfplan_destroy
          retention-days: 1

  # 4. Job de Destroy: Baixa o plano de destruição e destrói a infraestrutura
  terraform-destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    needs: terraform-plan-destroy
    if: github.event.inputs.destroy == 'true'
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5.0.0
      
      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      
      - name: 'Terraform Init'
        run: terraform init
        
      - name: 'Download Plan Destroy Artifact'
        uses: actions/download-artifact@v4
        with:
          name: tfplan_destroy
          path: ${{ env.WORKING_DIRECTORY }}
          
      - name: 'Terraform Destroy'
        run: terraform apply -destroy -auto-approve tfplan_destroy
